### ISSUE TITLE
Move all test files into a `tests/` subdirectory

### ISSUE THREAD

**Issue by theRemix** [edsperanto/devleague--behavior-driven-shopping-list#11]
example:

```
tests/
  js/shopping_list_test.js
  js/shopping_list_item_test.js
  index.html
js/
  app.js ...
node_modules/
  ...
index.html
```
 
so that a user can go to http://localhost:8080/tests to run tests

**Comment by ed-scaped** [comment]
fixed issue

**Comment by theRemix** [comment]
http://localhost:8080/tests works
however, there is still http://localhost:8080/tests.html lingering

clean that up (delete it) then close this task
