### ISSUE TITLE
create test instances of ShoppingList in isolation

### ISSUE THREAD

**Issue by theRemix** [edsperanto/devleague--behavior-driven-shopping-list#17]
use the `beforeEach()` mocha hook to create new test instances for each test

see: https://github.com/edsperanto/devleague--behavior-driven-shopping-list/blob/master/js/shopping_list_item_test.js#L68

if other tests were added in the future, that mutate `myList`, this test may unexpectedly **fail**

**Comment by ed-scaped** [comment]
fixed

**Comment by theRemix** [comment]
✅ lgtm!
